### ISSUE TITLE
提供英文名词搜索功能

### ISSUE THREAD

**Issue by ice1000** [banana-space/banana-space#10]
比如搜 fibration 给出纤维化这样。想要直接能跳转到词条的。如果是用现在的搜索的话，讲义里面会有很多 hit 的。

**Comment by abccsss** [comment]
直接跳转可以 (且应该) 通过创建重定向实现. 搜索包含讲义的结果是我有意加上的功能, 因为讲义很多时候讲得比百科更细致.
