### ISSUE TITLE
mediawiki 更新？

### ISSUE THREAD

**Issue by ldXiao** [banana-space/banana-space#12]
https://www.mediawiki.org/wiki/Version_lifecycle/en
目前mediawiki 1.35.13 是legacy LTS，在今年11月已经到达维护生命周期的终点。不知道有没有安排升级到更新的版本。

假如有计划长期维持跟mediawiki同步，那么合理的代码管理方式是把现有repo拆分，把banana skin， static script之类的部分单列为独立的git repo。然后主体部分包含了对mediawiki源代码改动的部分作为一个mediawiki的Fork来维护。

假如没有计划与mediawiki同步，准备停留在1.35.1，那么最好的方式是在本repo只提供一个非生产环境的clean start代码， 用docker-compose等方式来部署生产环境。现有的代码对不接触生产环境的开发者而言是很难维护的

**Comment by abccsss** [comment]
对 MW 内核的改动导致不方便（也没必要）紧跟 MW 更新，因此目前计划每隔几个 MW 版本更新一次。皮肤和插件目前还不互相独立，缺少彼此都不能完全正常工作，因此暂时不适合分开。如何配置环境在 README 里有详细说明。
