### ISSUE TITLE
tikz的execute at……的问题

### ISSUE THREAD

**Issue by hbghlyj** [banana-space/banana-space#13]
当使用 execute at begin node / execute at end node /
execute at begin cell / execute at end cell /
execute at begin function / execute at end function /
execute at begin scope / execute at end scope /
execute at begin picture / execute at end picture 时可能会出现问题。

例如
```tex
\begin{tikzpicture}
  \def\C{2}
  \node[execute at begin node={\def\C{1}}] {\C};
\end{tikzpicture}
```
在banana-space的结果为2：
![image](https://github.com/banana-space/banana-space/assets/53823634/34f0b66d-2611-4775-8694-40868a9230ae)
在LaTeX的结果为1：
![image](https://github.com/banana-space/banana-space/assets/53823634/06c5b6a5-db71-4438-9c84-33cb2fa3bfa3)

**Comment by abccsss** [comment]
[btex](https://github.com/banana-space/btex) 中 `tikzpicture` 并非完全与 LaTeX 格式兼容，只是一个接口，以适用大部分情况。若有进一步建议，请移步该项目。
