### ISSUE TITLE
\def 的问题

### ISSUE THREAD

**Issue by hbghlyj** [banana-space/banana-space#14]
例如
```tex
\def\test #1 #2 {#2 #1}
\test 12 34
```
在banana-space为`2 134`
![image](https://github.com/banana-space/banana-space/assets/53823634/737185a5-1ea8-4928-ba5b-e0a61c951c48)

在LaTeX为`34 12`
![image](https://github.com/banana-space/banana-space/assets/53823634/27990f2a-bb1a-43b5-9b8a-9802b20f79ea)

**Comment by abccsss** [comment]
[btex](https://github.com/banana-space/btex) 的设计并不兼容 TeX，`\def` 的意义也不同，因此，不要期望二者输出相同。
