### ISSUE TITLE
我想在bananaspace之上开发一些东西，但是遇到了问题

### ISSUE THREAD

**Issue by duoduo70** [banana-space/banana-space#2]
我试图构建bananaspace，除了banana插件外一切顺利，但是banana插件出现了各种错误，这是没有开发完吗？
以及我应该怎么把btex-monaco嵌入进编辑帖子的界面？
我应该怎么使用btex和tikz2svg进行编译TeX的工作？就像banana-space做的那样？
感谢

我的环境：
mariaDB Apache2+php Debain11

**Comment by abccsss** [comment]
这里的代码就是服务器上运行的代码。请提供你的错误信息。

**Comment by duoduo70** [comment]
MediaWiki internal error.

Original exception: [5221d8bcc58f39c0e5298467] /index.php/%E9%A6%96%E9%A1%B5 Error from line 248 of /var/www/banana-space/extensions/Banana/includes/BananaHooks.php: Call to undefined function curl_init()
Backtrace:
#0 /var/www/banana-space/extensions/Banana/includes/BananaHooks.php(97): BananaHooks::http_post_json()
#1 /var/www/banana-space/includes/HookContainer/HookContainer.php(320): BananaHooks::onParserBeforeInternalParse()
#2 /var/www/banana-space/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#3 /var/www/banana-space/includes/HookContainer/HookRunner.php(2901): MediaWiki\HookContainer\HookContainer->run()
#4 /var/www/banana-space/includes/parser/Parser.php(1539): MediaWiki\HookContainer\HookRunner->onParserBeforeInternalParse()
#5 /var/www/banana-space/includes/parser/Parser.php(651): Parser->internalParse()
#6 /var/www/banana-space/includes/content/WikitextContent.php(374): Parser->parse()
#7 /var/www/banana-space/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#8 /var/www/banana-space/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#9 /var/www/banana-space/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#10 /var/www/banana-space/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#11 /var/www/banana-space/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#13 /var/www/banana-space/includes/Revision/RenderedRevision.php(197): call_user_func()
#14 /var/www/banana-space/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /var/www/banana-space/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#16 /var/www/banana-space/includes/page/Article.php(810): PoolCounterWork->execute()
#17 /var/www/banana-space/includes/actions/ViewAction.php(74): Article->view()
#18 /var/www/banana-space/includes/MediaWiki.php(527): ViewAction->show()
#19 /var/www/banana-space/includes/MediaWiki.php(313): MediaWiki->performAction()
#20 /var/www/banana-space/includes/MediaWiki.php(940): MediaWiki->performRequest()
#21 /var/www/banana-space/includes/MediaWiki.php(543): MediaWiki->main()
#22 /var/www/banana-space/index.php(53): MediaWiki->run()
#23 /var/www/banana-space/index.php(46): wfIndexMain()
#24 {main}

Exception caught inside exception handler: [5221d8bcc58f39c0e5298467] /index.php/%E9%A6%96%E9%A1%B5 Error from line 248 of /var/www/banana-space/extensions/Banana/includes/BananaHooks.php: Call to undefined function curl_init()
Backtrace:
#0 /var/www/banana-space/extensions/Banana/includes/BananaHooks.php(97): BananaHooks::http_post_json()
#1 /var/www/banana-space/includes/HookContainer/HookContainer.php(320): BananaHooks::onParserBeforeInternalParse()
#2 /var/www/banana-space/includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#3 /var/www/banana-space/includes/HookContainer/HookRunner.php(2901): MediaWiki\HookContainer\HookContainer->run()
#4 /var/www/banana-space/includes/parser/Parser.php(1539): MediaWiki\HookContainer\HookRunner->onParserBeforeInternalParse()
#5 /var/www/banana-space/includes/parser/Parser.php(651): Parser->internalParse()
#6 /var/www/banana-space/includes/content/WikitextContent.php(374): Parser->parse()
#7 /var/www/banana-space/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#8 /var/www/banana-space/includes/Revision/RenderedRevision.php(263): AbstractContent->getParserOutput()
#9 /var/www/banana-space/includes/Revision/RenderedRevision.php(235): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached()
#10 /var/www/banana-space/includes/Revision/RevisionRenderer.php(215): MediaWiki\Revision\RenderedRevision->getSlotParserOutput()
#11 /var/www/banana-space/includes/Revision/RevisionRenderer.php(152): MediaWiki\Revision\RevisionRenderer->combineSlotOutput()
#12 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}()
#13 /var/www/banana-space/includes/Revision/RenderedRevision.php(197): call_user_func()
#14 /var/www/banana-space/includes/poolcounter/PoolWorkArticleView.php(216): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#15 /var/www/banana-space/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#16 /var/www/banana-space/includes/page/WikiPage.php(1281): PoolCounterWork->execute()
#17 /var/www/banana-space/skins/BananaSkin/includes/BananaSkin.php(111): WikiPage->getParserOutput()
#18 /var/www/banana-space/includes/skins/SkinMustache.php(59): BananaSkin->getTemplateData()
#19 /var/www/banana-space/includes/skins/SkinTemplate.php(144): SkinMustache->generateHTML()
#20 /var/www/banana-space/includes/OutputPage.php(2615): SkinTemplate->outputPage()
#21 /var/www/banana-space/includes/exception/MWExceptionRenderer.php(153): OutputPage->output()
#22 /var/www/banana-space/includes/exception/MWExceptionRenderer.php(65): MWExceptionRenderer::reportHTML()
#23 /var/www/banana-space/includes/exception/MWExceptionHandler.php(106): MWExceptionRenderer::output()
#24 /var/www/banana-space/includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report()
#25 /var/www/banana-space/includes/MediaWiki.php(579): MWExceptionHandler::handleException()
#26 /var/www/banana-space/index.php(53): MediaWiki->run()
#27 /var/www/banana-space/index.php(46): wfIndexMain()
#28 {main}

**Comment by abccsss** [comment]
你需要先安装 php-curl
