### ISSUE TITLE
自定义配色方案

### ISSUE THREAD

**Issue by rqy2002** [banana-space/banana-space#3]
是否可以加一个在参数设置里面调整配色方案的功能？
有一些人反应更喜欢前段时间更新之前的颜色。

**Comment by abccsss** [comment]
是可行的，MediaWiki 支持换肤，但我们皮肤也包括页面布局的代码，直接复制一个会导致代码重复，不知道有没有更好的办法。

另外，现在很少有网站支持换肤功能了（除明暗主题外），我打算根据用户反馈改进目前配色，而不是做多个版本。我也希望黄橙配色成为香蕉空间的标志。
