### ISSUE TITLE
在星号打出来的列表中第一项如果是链接会被吞

### ISSUE THREAD

**Issue by ice1000** [banana-space/banana-space#4]
![image](https://user-images.githubusercontent.com/16398479/170802495-8e358b1a-12e5-4210-a0fc-370d4d5d3ff6.png)

如图

**Comment by abccsss** [comment]
[已修复](https://github.com/banana-space/btex/commit/22d8ac1f57bb81f8e514ebe8f2f3574c21d738b7)
