### ISSUE TITLE
KaTeX 版本问题

### ISSUE THREAD

**Issue by ice1000** [banana-space/banana-space#5]
我注意到 1a42d6a310115e8d6fdec26df898ff2a9284ff70 这个提交更新了 KaTeX 的 CSS 链接，但是 bTeX 使用的 KaTeX 是一个比较[古老的版本](https://github.com/banana-space/btex/blob/c3fbb363315c87cc9c46c31ba804a4c8c413aceb/yarn.lock#L33-L36)，我觉得可能 bTeX 的依赖需要更新一下。

**Comment by abccsss** [comment]
[已修复](https://github.com/banana-space/btex/commit/99d671e57f801e44d7d7e8572c9a6e37298dda49)
