### ISSUE TITLE
打印模式 CSS

### ISSUE THREAD

**Issue by Trebor-Huang** [banana-space/banana-space#7]
目前打印时有可能框的顶部或者底部一小条会被分到另一页，这个应该可以通过CSS `break-inside` `break-before` `break-after` 属性禁止。

还有值得讨论的是是否应该允许定理和引用在分页时从中间断开。定理比较短，所以可能不允许断开会比较合理。

**Comment by abccsss** [comment]
比如[幺半范畴](https://www.bananaspace.org/wiki/%E5%B9%BA%E5%8D%8A%E8%8C%83%E7%95%B4)的定义就很长, 未来超过一页的定理应该也不会少见.

我一直没好好做打印的 css, 首先得调好字号和行距, 比如模板框和术语翻译就和其他部分不相容. 有空慢慢弄吧, 你能帮忙也行.

**Comment by Trebor-Huang** [comment]
顺便，做这个的时候也可以加一个命令强制分页，在正常浏览时没有作用。

或者干脆允许任意html节点的插入？

**Comment by abccsss** [comment]
强制分页会导致前一页只有一小段文字。有什么情况需要这个功能吗？

任意 HTML 是可以实现的，用模板就好，模板是 wikitext 而不是 btex。
