### ISSUE TITLE
KaTeX 有时 y 轴会轻微溢出

### ISSUE THREAD

**Issue by Trebor-Huang** [banana-space/banana-space#8]
https://github.com/banana-space/banana-space/blob/5b17723acce7491a4d3403a6dcdbbaa2001a501f/skins/BananaSkin/resources/skin.less#L1189

这里可能对 y 轴用 `visible` 会略微好看一点，不然一些上下标偶尔会被剪头发。这会有什么意外的副作用吗？

**Comment by abccsss** [comment]
这会导致公式右边显示滚动条：

![图片](https://user-images.githubusercontent.com/23280392/193155290-bf4fd0a5-3ca1-4650-8985-e8c1abcd2457.png)

**Comment by Trebor-Huang** [comment]
所以这是什么原理，标准里面说visible是不会显示滚动条的
